### ISSUE TITLE
Homepage - Solutions section: Use a 'Slick carousel' for the steps custom posts as per instruction in the Project Scope #22.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#10] opened 2015-05-04 07:06 UTC
Expected: When using a slick carousel, display of post items should be flexible/unlimited in the homepage.

**Comment by arielcebudigital** [comment] 2015-05-13 07:37
base on the design brief:
Solutions - This is a process steps 1-5 to show how they go about providing a solution., I already used slick carousel you can see the output by doing responsive test., Slide feature will not work if 5 items will display in desktop.

**Comment by dsigue** [comment] 2015-05-21 03:18
For clarification:
since according to the scope solutions section must used slick carousel fo the steps custom postm however it only 5 items display thats why carousel will not work, but when adding one more item on solution it still limit 5 items. Does the desktop view doesn't allow slick carousel functions just like the responsive do, please refer scope #22. Please advise. Thanks

**Comment by arielcebudigital** [comment] 2015-05-22 03:06
from our point of view, we dont allow the steps to scroll since this is a process and it does not make sense, if steps will rotate if on descktop view that have only 5 steps displayed, but anyways the steps used is a slick banner funcitionality, it will only rotate if it is viewed on mobile since it cant fit the steps on the screen, let us know your thoughts.

**Comment by dsigue** [comment] 2015-05-22 03:32
If that what you say so, then this must be closed as invalid/not a bug, but what I'm trying to imply is, the items only limit to 5 item display, that's why slick carousel on desktop is not applied however when it becomes 6 items or more that's the time slick carousel will applied. Scope mention slick must be applied. Please let us know your insight about this function. Thanks

**Comment by arielcebudigital** [comment] 2015-05-22 03:35
Actually it apply in the desktop as well, but we only limit it to 5.

**Comment by dsigue** [comment] 2015-05-22 03:41
Okay, if that's the way it is, then I move to closed this ticket as invalid. Ensure that in the near future when items need to become 6 and more slick carousel must be applied. Thanks then.

**Closed by dsigue** 2015-05-22 03:41 UTC
Labels: bug, invalid
